---
- name: Restart yanic
  service: name=yanic state=restarted

- name: Restart yanic-publish
  service: name=yanic-publish.timer state=restarted

- name: Reload systemd
  command: systemctl daemon-reload
