---

- name: Install fastd
  apt: name=fastd state=latest

- name: Install haveged (to create entropy)
  apt: name=haveged

- name: Systemd unit for fastd
  copy: src=fastd@.service dest=/etc/systemd/system/fastd@.service
  notify:
  - Reload systemd
  - Restart fastd

- name: Disable fastd default instance
  service: name=fastd enabled=no

- name: Create directories
  file: path=/etc/fastd/{{ fastd_instance }}/peers state=directory

- name: Configure fastd
  template: src=fastd.conf.j2 dest=/etc/fastd/{{ fastd_instance }}/fastd.conf
  notify: Restart fastd

- name: Generate fastd secret
  fastd_key: path=/etc/fastd/{{ fastd_instance }}/secret.conf
  notify: Restart fastd

- name: Enable fastd {{ fastd_instance }}
  service: name=fastd@{{ fastd_instance }} enabled=yes
