---

- name: Download and install go
  unarchive: src=https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz dest=/usr/local copy=no

- name: Configure go
  copy: src=go.sh dest=/etc/profile.d/go.sh
